const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('teamyra', {
  rendererReady: () => ipcRenderer.send('teamyra:renderer-ready'),
  platform: process.platform,
  updateStatus: () => ipcRenderer.invoke('teamyra:update-status'),
  checkUpdates: () => ipcRenderer.invoke('teamyra:update-check'),
  installUpdate: () => ipcRenderer.invoke('teamyra:update-install'),
  onUpdateState: (callback) => ipcRenderer.on('teamyra:update-state', (_event, payload) => callback(payload)),
  providers: () => ipcRenderer.invoke('teamyra:providers'),
  mcpConnections: () => ipcRenderer.invoke('teamyra:mcp-connections'),
  connectMcp: (providerId) => ipcRenderer.invoke('teamyra:mcp-connect', providerId),
  jobs: () => ipcRenderer.invoke('teamyra:jobs'),
  transcript: (jobId, offset = 0) => ipcRenderer.invoke('teamyra:transcript', jobId, offset),
  startTask: (options) => ipcRenderer.invoke('teamyra:task-start', options || {}),
  cancelTask: (jobId) => ipcRenderer.invoke('teamyra:task-cancel', jobId),
  pickProject: () => ipcRenderer.invoke('teamyra:pick-project'),
  timeline: (options) => ipcRenderer.invoke('teamyra:timeline', options || {}),
  searchLogs: (options) => ipcRenderer.invoke('teamyra:logs-search', options || {}),
  usage: (options) => ipcRenderer.invoke('teamyra:usage', options || {}),
  chatgptStatus: () => ipcRenderer.invoke('teamyra:chatgpt-status'),
  openChatgpt: () => ipcRenderer.invoke('teamyra:chatgpt-open'),
  closeChatgpt: () => ipcRenderer.invoke('teamyra:chatgpt-close'),
  reloadChatgpt: () => ipcRenderer.invoke('teamyra:chatgpt-reload'),
  reconnectChatgpt: () => ipcRenderer.invoke('teamyra:chatgpt-reconnect'),
  newChatgptChat: () => ipcRenderer.invoke('teamyra:chatgpt-new-chat'),
  stopChatgpt: () => ipcRenderer.invoke('teamyra:chatgpt-stop'),
  sendChatgptTask: (text) => ipcRenderer.invoke('teamyra:chatgpt-send', text),
  chatgptConversation: () => ipcRenderer.invoke('teamyra:chatgpt-conversation'),
  openChatgptConversation: (value) => ipcRenderer.invoke('teamyra:chatgpt-open-conversation', value),
  setChatgptVisible: (visible) => ipcRenderer.invoke('teamyra:chatgpt-visible', visible === true),
  setChatgptBounds: (bounds) => ipcRenderer.invoke('teamyra:chatgpt-bounds', bounds || {}),
  chatgptWorkspaceStatus: () => ipcRenderer.invoke('teamyra:chatgpt-workspace-status'),
  configureChatgptWorkspace: (workspace, permissions) => ipcRenderer.invoke('teamyra:chatgpt-workspace-configure', workspace, permissions || {}),
  selectChatgptWorkspace: () => ipcRenderer.invoke('teamyra:chatgpt-select-workspace'),
  chatgptChanges: () => ipcRenderer.invoke('teamyra:chatgpt-changes'),
  revertChatgptChanges: (paths, confirm = false) => ipcRenderer.invoke('teamyra:chatgpt-revert', paths || ['.'], confirm === true),
  attachChatgptFile: (filePath) => ipcRenderer.invoke('teamyra:chatgpt-attach-file', filePath),
  addAccount: (providerId, name) => ipcRenderer.invoke('teamyra:add-account', providerId, name),
  updateAccount: (providerId, profileId, patch) => ipcRenderer.invoke('teamyra:update-account', providerId, profileId, patch || {}),
  memoryList: (options) => ipcRenderer.invoke('teamyra:memory-list', options || {}),
  memorySearch: (options) => ipcRenderer.invoke('teamyra:memory-search', options || {}),
  memoryGet: (projectPath, memoryId) => ipcRenderer.invoke('teamyra:memory-get', projectPath, memoryId),
  memoryAdd: (options) => ipcRenderer.invoke('teamyra:memory-add', options || {}),
  memoryUpdate: (options) => ipcRenderer.invoke('teamyra:memory-update', options || {}),
  memoryArchive: (projectPath, memoryId, reason = '') => ipcRenderer.invoke('teamyra:memory-archive', projectPath, memoryId, reason),
  memoryContext: (options) => ipcRenderer.invoke('teamyra:memory-context', options || {}),
  worktrees: () => ipcRenderer.invoke('teamyra:worktrees'),
  worktreeStatus: (worktreeId) => ipcRenderer.invoke('teamyra:worktree-status', worktreeId),
  worktreeDiff: (worktreeId, maxChars = 80000) => ipcRenderer.invoke('teamyra:worktree-diff', worktreeId, maxChars),
  createWorktree: (options) => ipcRenderer.invoke('teamyra:worktree-create', options || {}),
  rebaseWorktree: (worktreeId, confirm = false) => ipcRenderer.invoke('teamyra:worktree-rebase', worktreeId, confirm),
  beginConflictResolution: (worktreeId, confirm = false) => ipcRenderer.invoke('teamyra:conflict-begin', worktreeId, confirm),
  conflictDetail: (worktreeId, conflictPath) => ipcRenderer.invoke('teamyra:conflict-detail', worktreeId, conflictPath),
  resolveConflict: (worktreeId, conflictPath, options) => ipcRenderer.invoke('teamyra:conflict-resolve', worktreeId, conflictPath, options || {}),
  continueConflictResolution: (worktreeId, confirm = false) => ipcRenderer.invoke('teamyra:conflict-continue', worktreeId, confirm),
  abortConflictResolution: (worktreeId, confirm = false) => ipcRenderer.invoke('teamyra:conflict-abort', worktreeId, confirm),
  mergeWorktree: (worktreeId, confirm = false) => ipcRenderer.invoke('teamyra:worktree-merge', worktreeId, confirm),
  discardWorktree: (worktreeId, options) => ipcRenderer.invoke('teamyra:worktree-discard', worktreeId, options || {}),
  openTerminal: (options) => ipcRenderer.invoke('teamyra:terminal-open', options || {}),
  writeTerminal: (id, data) => ipcRenderer.send('teamyra:terminal-input', { id, data }),
  resizeTerminal: (id, cols, rows) => ipcRenderer.send('teamyra:terminal-resize', { id, cols, rows }),
  closeTerminal: (id) => ipcRenderer.invoke('teamyra:terminal-close', id),
  onTerminalData: (callback) => ipcRenderer.on('teamyra:terminal-data', (_event, payload) => callback(payload)),
  onTerminalExit: (callback) => ipcRenderer.on('teamyra:terminal-exit', (_event, payload) => callback(payload))
});
